### ISSUE TITLE
Contao 4.4 no Scripts visible

### ISSUE THREAD

**Issue by GMTeams** [trilobit-gmbh/contao-formvalidation-bundle#1]
Contao 4.4
trilobit-gmbh/contao-formvalidation-bundle 1.0.11
Seitenlayout: "Skripte zusammenfassen" = not active

In FE, I don't see any livevalidation or trilobit scripts.
When I configure e.g. a text field with "Eingabeprüfung: Erweiterte alphanumerische Zeichen" there is no CSS class like "valid" or "not-valid". So there is no livevalidation.

In BE in system settings, there is an entry for formvalidation extension, so installation should be ok.

Maybe its a configuration problem, do you know what I can do?
There are various other 3rd party extensions installed, e.g. contao-bootstrap/form, terminal42/contao-ajaxform.

Thanks.

**Comment by GMTeams** [comment]
Now I did (for other reasons) some changes in the page layout and in the settings.
The scripts are now shown and working, I think they were not shown because of (script?) caching.
Thanks anyway.

**Comment by trilobit-gmbh** [comment]
;-)
