### ISSUE TITLE
Fehler bei deinstalliertem Newsletter-Modul

### ISSUE THREAD

**Issue by tn34de** [trilobit-gmbh/contao-formvalidation-bundle#16]
Hallo zusammen,

wir haben in einem Projekt den integrierten Newsletter von Contao, gegen einen eigenen ausgetauscht. Seitdem bekommen wir immer wieder Fehler von ModuleNewsletterSubscribe.php. 
Der Extends \Contao\ModuleSubscribe wird nicht mehr gefunden.

Ich habe das jetzt mal auf die Schnelle in der  config.php auskommentiert.
```php
#$GLOBALS['FE_MOD']['newsletter']['subscribe'] = ModuleNewsletterSubscribe::class;
#$GLOBALS['FE_MOD']['newsletter']['unsubscribe'] = ModuleNewsletterUnsubscribe::class;
```
Seit diese Contao-Module deinstallierbar sind, sollte eine Abhängigkeitsprüfung durchgeführt werden.

Gruß 
Andy von TN34.DE

**Comment by trilobit-gmbh** [comment]
1.1.1
