### ISSUE TITLE
Mit Contao 4.13.8 kompatibel?

### ISSUE THREAD

**Issue by minstyle** [trilobit-gmbh/contao-formvalidation-bundle#19]
Contao: 4.13.8
PHP 7.4
trilobit-gmbh/contao-formvalidation-bundle (1.1.1)

Website mit Kontaktformular über Formulargenerator erstellt. Dann das aktuelle Bundle installiert. Allerdings werden im Frontend (DOM) keine Veränderungen (neue CSS-Klassen) bei Pflichtfeldern angezeigt.

Lediglich im Header werden folgende Dateien eingebunden:

`<link rel="stylesheet" href="bundles/trilobitformvalidation/css/trilobit_livevalidation.css?v=1167261b">`
`<script src="bundles/trilobitformvalidation/js/livevalidation_standalone.compressed.js?v=1167261b"></script>`
`<script src="bundles/trilobitformvalidation/js/trilobit_livevalidation.js?v=1167261b"></script>`

**Comment by trilobit-gmbh** [comment]
Hallo,
ich habe das gerade in einer einfachen Contao getestet mit den von Dir angegebenen Versionen. Ich habe nichts weiter installiert (keine weiteren Bundles/Erweiterungen, JS oder CSS).
Da funktioniert die Formvalidation wie gewünscht.
Wenn alles korrekt installiert ist, müssen (bei einem Formular) 4 Dateien geladen werden:
```
<!--- Einfaches CSS für "rot" / "grün" Färbung der Felder --->
<link rel="stylesheet" href="bundles/trilobitformvalidation/css/trilobit_livevalidation.css?v=1167261b">

<!--- Die eigentlichen Validierungs-Javascript-Funktionen --->
<script src="bundles/trilobitformvalidation/js/livevalidation_standalone.compressed.js?v=1167261b"></script>

<!--- Funktionen für Radio/Checkbox und die Ansteuerung der Validierungs-Javascript-Funktionen --->
<script src="bundles/trilobitformvalidation/js/trilobit_livevalidation.js?v=1167261b"></script>

<!--- Konfiguration. Wird vom System automatisch aus den im Backend eingestellten Feld-Optionen im Formulargenerator erzeugt --->
<script src="assets/js/lv_tl_form_1_fc254d6a6193e99aa1305565f057bc0a.js"></script>
```

Wenn die Konfiguration nicht eingebunden ist kann dies mehrere Gründe haben; z. B.:

- Die Einbindung in https://github.com/trilobit-gmbh/contao-formvalidation-bundle/blob/main/src/Resources/contao/config/config.php wird durch Dritte überschrieben/geändert
- Im Formular sind keine Pflichtfelder und/oder andere Validierungen hinterlegt
- Es werden Formularerweiterungen verwendet, die die Formvalidation nicht kennt

Ein paar ergänzende Fragen:

- Wie bindest Du die Formulare ein?
- Ist die Konfiguration eventuell doch eingebunden?
- Werden Javascript-Fehler geworfen (siehe Konsole im Browser > Entwicklertools)
- Überschreibt ein eigenes CSS das default-CSS

Bei Bedarf kann ich einen einfachen (!) und schnellen (!) Blick auf die Website und das Formular werfen (Frontend) und ggf weitere Hinweise geben (peter.adelmann@trilobit.de)
Weitergehender Support ist dann aber (leider) kostenpflichtig.

![screencapture-contao-413-testing-trilobit-home-2022-09-08-12_49_10](https://user-images.githubusercontent.com/7868402/189103857-55c19d78-7007-4982-a052-fe43040e9356.png)


Viele Grüße
Peter

**Comment by trilobit-gmbh** [comment]
Mit Contao 4.13.8 kompatibel?
Ja! ;-)

**Comment by minstyle** [comment]
Vielen Dank für die Rückmeldung 👍

Wie ich sehe, werden bei mir auch die 4 Dateien wie von dir beschrieben, in das Template eingebunden. Da habe ich wohl eine Datei übersehen.

Hier meine Antworten zu deinen Fragen:

> Die Einbindung in https://github.com/trilobit-gmbh/contao-formvalidation-bundle/blob/main/src/Resources/contao/config/config.php wird durch Dritte überschrieben/geändert

Nicht das ich wüsste.

> Im Formular sind keine Pflichtfelder und/oder andere Validierungen hinterlegt

Wie Eingangs beschrieben sind hier Pflichtfelder definiert. Bspw. das Eingabefeld `E-Mail` inkl. Validierung.

> Es werden Formularerweiterungen verwendet, die die Formvalidation nicht kennt

Nein., es werden keine weiteren Formularerweiterungen genutzt bzw. sind installiert.

> Wie bindest Du die Formulare ein?

Über das Contao-Inhaltselement "Formulare".

> Ist die Konfiguration eventuell doch eingebunden?

Was meinst du damit?

> Werden Javascript-Fehler geworfen (siehe Konsole im Browser > Entwicklertools)

Nein.

> Überschreibt ein eigenes CSS das default-CSS

Zu Testzwecken habe ich alle "eigenen" CSS-Dateien deaktiviert. Leider ohne Erfolg. Es findet keine Live Validierung statt.

![image](https://user-images.githubusercontent.com/2649562/189126264-898f52b5-dc14-4203-92a8-20d37ba22bf6.png)

**Comment by trilobit-gmbh** [comment]
Also der Screenshot zeigt eine live Validierung:

- Firma, Vorname, Straße, Postleitzahl und Ort sind keine Pflichtfelder > leer > "grün" > Validierung funktioniert
- Name ist ein leeres Pflichtfeld > "rot" > fehlerhafte bzw keine Eingabe > Validierung funktioniert
- Telefon ist ein Pflichtfeld > Eingabe ist keine Telefonnummer > "rot" > Validierung funktioniert
- E-Mail ist ein Pflichtfeld > Eingabe ist keine E-Mail Adresse > "rot" > Validierung funktioniert
- Zum Feld Nachricht kann ich erst einmal nichts sagen

Bei allen Feldern gehe ich davon aus, dass der Type im Backend korrekt gesetzt ist (Telefonnummer bei Telefonnummer, E-Mail Adresse bei ...)

Hast Du angepasste Templates? Hast Du Sprachdateien angepasst? Hinter den als falsch erkannten Feldern muss im Fehlerfall ein Text angezeigt werden; z. B. 
```
<span class=" LV_validation_message LV_invalid">Bitte geben Sie eine gültige E-Mail-Adresse ein!</span>
```
Dieser Hinweis wird immer direkt nach dem Eingabefeld eingebunden.

Aber ohne weitere Infos und/oder einem Link lässt sich hier nicht viel mehr sagen. 

Weitergehender Support ist dann aber (leider) kostenpflichtig.

**Comment by trilobit-gmbh** [comment]
Ich schließe diesen Issue einmal. Ein Fehler ist nicht zu sehen; läuft in verschiedenen Instanzen korrekt.
Für weiteren Support bitte melden ;-)
