### ISSUE TITLE
Login-Formular: "strlen(): Argument #1 ($str) must be of type string, null given"

### ISSUE THREAD

**Issue by andre5tz** [trilobit-gmbh/contao-formvalidation-bundle#23]
Hallo,

nach einem Update von der Version 1.1 auf 2.0 bekomme ich eine Fehlermeldung beim Aufruf der Contao Login Seite.
Contao 4.13.15 und PHP 8.1

In der var/logs finde ich dazu zwei Einträge:
`[2023-01-24T14:46:53.982921+01:00] request.INFO: Matched route "tl_page.745". {"route":"tl_page.745","route_parameters":{"_token_check":true,"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","_format":"html","_canonical_route":"tl_page.745","parameters":"","pageModel":{"Contao\\PageModel":[]},"_route":"tl_page.745","_route_object":{"Contao\\CoreBundle\\Routing\\Page\\PageRoute":[]}},"request_uri":"https://www.domain.de/login.html","method":"GET"} []`

`[2023-01-24T14:46:54.026269+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: "strlen(): Argument #1 ($str) must be of type string, null given" at /.../vendor/trilobit-gmbh/contao-formvalidation-bundle/src/Resources/contao/modules/ModuleLogin.php line 32 {"exception":"[object] (TypeError(code: 0): strlen(): Argument #1 ($str) must be of type string, null given at /.../vendor/trilobit-gmbh/contao-formvalidation-bundle/src/Resources/contao/modules/ModuleLogin.php:32)"} []`

Bin erst mal wieder auf die Version 1.1 zurück, hoffe aber, dass Euch die Meldung hilft und Ihr damit was anfangen könnt.

Viele Grüße und herzlichen Dank.
André

**Comment by trilobit-gmbh** [comment]
Ja, Danke ;-) Diese Meldung habe ich auch schon gesehen heute :-(

**Comment by andre5tz** [comment]
Herzlichen Dank für die superschnelle Korrektur :-)
Mit der Version 2.0.2, kurz getestet, klappt es wieder wie gewohnt.

**Comment by trilobit-gmbh** [comment]
@andre5tz Vielen Dank für die schnelle Prüfung und das Schließen den Issue ;-) Viele Grüße!
