### ISSUE TITLE
Validation starts at page load instead of submit

### ISSUE THREAD

**Issue by GMTeams** [trilobit-gmbh/contao-formvalidation-bundle#3]
In my form the validation starts immediately when the page is loaded. So you can see the error messages immediately, but this should only occur when you click the submit button.

I my first test, this didn't happen. Now I made some changes in the form and page layout, and this happens.

There are no script errors, the _LV_invalid_field_ classes for validation are set correctly, but to early.
To prevent this, I tried many things like deleting all other scripts and FE modules. Caches cleared.
I can provide a test link: https://bit.ly/2Cm3SId

Maybe you have a tip what I can check? Thanks!

**Comment by trilobit-gmbh** [comment]
Hallo,
die beschriebene Funktion ist die Grundfunktionalität des verwendeten Javascript.
Du kannst jedoch einen kleinen Workaround bauen, damit initial keine CSS-Klasse gesetzt wird (bzw genauer gesagt, dass beim ersten Laden der Seite die CSS-Klassen wieder herunter genommen werden).

In jQuery könntest Du das wie folgt lösen:
```
jQuery('span[class*="LV_"]').remove();
```
Damit werden alle CSS-Klassen, die die Formvalidation setzt entfernt. Beim Ausfüllen selbst und den zugehörigen Checks werden die Klassen dann wieder entsprechend gesetzt.

Viele Grüße
Peter
