### ISSUE TITLE
textarea LV_invalid_field not working

### ISSUE THREAD

**Issue by dobirr** [trilobit-gmbh/contao-formvalidation-bundle#5]
Bei Textareas wird die klasse " LV_invalid_field" nicht gesetzt, somit kann ich obwohl es mandatory ist die Farbe nicht hervorheben.

**Comment by trilobit-gmbh** [comment]
Hallo dobirr,

hast Du ein Bspl? Gerne auch per PM (peter.adelmann@trilobit.de).
In meiner Testinstallation verhält sich das "textarea" identisch zum Type "text".
Initial wird keine "LV_" Klasse gesetzt. Erst nach einem "blur" wird der Check für das aktuelle Feld ausgeführt. Dann steht auch die fragliche Klasse zur Verfügung.
Die Prüfung wird auch ausgeführt beim Abschicken des Formular.

VG Peter
