### ISSUE TITLE
Loginform Bug

### ISSUE THREAD

**Issue by Witti2** [trilobit-gmbh/contao-formvalidation-bundle#8]
Hello, we installed the extension and noticed the following.

When registering, Valid is only output if you have entered at least 8 characters for the password. The error message also indicates the at least 8 characters.

When you log in, however, as soon as you enter 1 character, Valid is displayed. I think that this is a mistake because the password should also be valid when you log in if you have entered at least 8 characters.

greetings

**Comment by trilobit-gmbh** [comment]
We have improved the behavior and created a merge request. This will probably be merged into the origin branch in the next few days.

**Comment by trilobit-gmbh** [comment]
new version 1.0.16 available
